<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>

        <EngineDir Condition="'$(EngineDir)' == ''">$(LOCALAPPDATA)\SpaceWayLauncher\engines\extracted</EngineDir>
        <ContentDir Condition="'$(ContentDir)' == ''">$(LOCALAPPDATA)\SpaceWayLauncher\content-extracted</ContentDir>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="nunit" />
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Content.SpaceWayBlueprints\Content.SpaceWayBlueprints.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Robust.Shared.Maths">
            <HintPath>$(EngineDir)\Robust.Shared.Maths.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
